### ISSUE TITLE
Wrong version of WOSS

### ISSUE THREAD

**Issue by ramok** [uwsignet/DESERT_Underwater#1]
In commonVariables.sh setted **WOSS_VERSION=1.5.1**, but in git committed only woss-1.3.8.tar.gz

**Comment by fedefava86** [comment]
Thanks @ramok for spotting this. Taking a look ASAP

**Comment by ramok** [comment]
BTW, there is no ns-real-time.patch in patches.tar.gz
I did't know if it suppose to be there :)

**Comment by fedefava86** [comment]
There should be. Probably something went wrong during release process :) Checking and fixing ASAP
